const Discord = require("discord.js");
const config = require("./botconfig.json");
const examplesEmbedExec = new Discord.MessageEmbed()
	.setTitle("📖 ┊ Examples of Galaxy Cowboy's commands")
	.attachFiles(['assets/osalien.jpg'])
	//.setThumbnail("attachment://osalien.jpg")
	.addField('\u200b', '\u200b')
	.addField("📊 Weekly Poll", `\`\`\`&${config.prefix}weekly "Title" "2020-06-22" "2020-06-28"\`\`\``)
	.addField("📊 Custom Weekly Poll", `\`\`\`${config.prefix}weekly "Title" "2020-06-22" "2020-06-28" "Custom Description"\`\`\``)
	.addField("📊 Custom Weekly Poll without dates", `\`\`\`${config.prefix}weekly "Title" "2020-06-22" "2020-06-28" "Custom Description" "no dates"\`\`\``)
	.addField("📊 Y/N Poll", `\`\`\`${config.prefix}poll "Do you like this?"\`\`\``)
	.addField("📊 Complex poll", `\`\`\`${config.prefix}poll "Which event do you want?" "Strikes" "Fractals" "Raid"\`\`\``)
	.addField("📊 Timed Weekly Poll", `\`\`\`${config.prefix}weekly time=7d "Which day are you free?"\`\`\``)
	.addField("📊 Timed Poll", `\`\`\`${config.prefix}poll time=6h "GW2 tonight?"\`\`\``)
	.addField("📊 See the results of a poll", `\`\`\`${config.prefix}end 61342378\`\`\``)
	.addField("📊 Call to action Weekly Poll", `\`\`\`${config.prefix}update 61342378\`\`\``)
	.addField('\u200b', '\u200b')
	.addField("<:status:747796552407449711>	Set status", `\`\`\`${config.prefix}setstatus "Playing GW2"\`\`\`Set your custom status`)
	.addField("<:status:747796552407449711>	Set timed status", `\`\`\`${config.prefix}setstatus time=3d "Out for the weekend"\`\`\`Set your custom timed status`)
	.addField("<:status:747796552407449711>	Set timed status", `\`\`\`${config.prefix}removestatus\`\`\`Remove your current status`)
	.addField("<:status:747796552407449711>	Set timed status", `\`\`\`${config.prefix}status @user\`\`\`Check status of user`)
	.addField('\u200b', '\u200b')
	.attachFiles(['assets/osalien.jpg'])
	.setFooter("The bot has been created by Zep, leader and founder of Galaxy Cowboys.\nFeel free to report bugs.", 'attachment://osalien.jpg')
    .setColor("#DDA0DD");
module.exports = examplesEmbedExec;