const Discord = require("discord.js");
const config = require("./botconfig.json");
const helpEmbed = new Discord.MessageEmbed()
	.setTitle("❓ ┊ Galaxy Cowboy's Commands")
	.attachFiles(['assets/osalien.jpg'])
	.addField('\u200b', '\u200b')
	.addField("<:gcstar:730505901529759784>	Bot Setup", `\`\`\`${config.prefix}setup\`\`\``+"Change Prefix\nChange Status Overview Channel")
	.addField("<:gcstar:730505901529759784>	See examples", `\`\`\`${config.prefix}examples\`\`\``)
	.addField('\u200b', '\u200b')
	.addField("📊 Create (Custom) Weekly Poll", `\`\`\`${config.prefix}weekly "Title" "Starting Date" "Ending Date" "Custom Description"\`\`\``+"Format: YYYY-MM-DD format\nAll fields are optional except for the Title, default starts today, ends in 7 days")
	.addField("📊 Create Y/N poll", `\`\`\`${config.prefix}poll "Question"\`\`\``)
	.addField("📊 Create complex poll [2-10 answers]", `\`\`\`${config.prefix}poll "Question" "Option 1" "Option 2" ["Option 3" ...]\`\`\`(quotes are necessary)`)
	.addField("📊 Timed polls that close automatically", `\`\`\`${config.prefix}{weekly/poll} time=X{s|m|h|d} ...\`\`\`X = length + secons, minutes, hours, days. 
	This can be added in all polls before "Poll Question / Weekly Title"`)
	.addField("📊 See results of a poll and close the voting", `\`\`\`${config.prefix}end ID\`\`\`where ID is the poll id which appears at the end of the poll`)
	.addField("📊 Call to action Weekly Poll", `\`\`\`${config.prefix}update ID\`\`\`where ID is the poll id which appears at the end of the poll`)
	.addField('\u200b', '\u200b')
	.addField("<:status:747796552407449711>	Set status", `\`\`\`${config.prefix}setstatus "Custom Status"\`\`\`Set your custom status`)
	.addField("<:status:747796552407449711>	Set timed status", `\`\`\`${config.prefix}setstatus time=3d "Custom Timed Status"\`\`\`Set your custom timed status`)
	.addField("<:status:747796552407449711>	Set timed status", `\`\`\`${config.prefix}removestatus\`\`\`Remove your current status`)
	.addField("<:status:747796552407449711>	Set timed status", `\`\`\`${config.prefix}status @user\`\`\`Check status of user`)
	.addField('\u200b', '\u200b')
	.addField("✉️  Invite", `\`\`\`${config.prefix}invite \`\`\`Bot invite link to share, website link, Support Server link, summary of bot.`)
	.addField('\u200b', '\u200b')
	.addField("🛠️	Set Status Channel where all statuses will be posted", `\`\`\`${config.prefix}setstatuschannel " #channel "\`\`\`Tip: Use a space after <"> as shown above so you can link the channel`)
	.addField('\u200b', '\u200b')
	.addField("<:paypal:734189737077637121>	Donate", `\`\`\`${config.prefix}donate\`\`\`Donate to help keeping the uptime of the bot`)
	.addField('\u200b', '\u200b')
	.addField("📜 TOS", `\`\`\`${config.prefix}TOS\`\`\`Terms of Service, Privacy Policy`)
	.addField('\u200b', '\u200b')
	.addField("About", "The bot has been created by Zep, leader and founder of Galaxy Cowboys. Feel free to report bugs.")
	.setFooter("Credits to Zheoni for being able to use the source code of Votabot and make this happen", 'attachment://osalien.jpg')
    .setColor("#DDA0DD");
module.exports = helpEmbed;